project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Biostatistics 1"
  navbar:
    background: primary
    search: true
    logo: "images/EPI_525.png"
    foreground: "#fff"
    collapse-below: sm
    right:
          - href: schedule.qmd
            text: Schedule
          - href: syllabus.qmd
            text: Syllabus
          - href: instructors.qmd
            text: Instructors
          - href: homework.qmd
            text: Homework

execute:
  freeze: auto

format:
  html:
    theme:
      - sandstone_NW.scss
    toc: true



